name: Deploy Nodejs code on ExCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on ExCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.128.126
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}
          script: cd /home/ubuntu/Production_Deployment
            git pull
            npm install
            pm2 restart 0
